version: 'nightly-{build}'
image: Ubuntu2004
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar gcc-multilib g++-multilib -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.1.5/haxe-4.1.5-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.1.5-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install HtmlParser
  - haxelib install markdown
  - haxelib install newgrounds
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  - lime rebuild extension-webm linux
  - haxelib install actuate
  - haxelib list
  - cd /home/appveyor/projects/bcb-linux

build_script:
  - haxelib run lime build linux

after_build:
  - tar -cvf bcb-nightly-linux.tar -C /home/appveyor/projects/bcb-linux/export/release/linux/bin .

artifacts:
- path: bcb-nightly-linux.tar
  name: bcb nightly linux
